>Hard_Clam
-------------------------KVQENFDLSKY--LGRWYENRRYSNL--------F
	SLFSNCVTAEYTALSETSVRVNNTGWKYLSNYYDNAIG-EAIVMSDGKLGVRF------
-	SEF--QPYEDYWVLSTDYTSYSIVWSCMET--PKGPIQFNSQYLWILSRSPDGVPDE-
-Q	
>Venus_Clam
--------------------KCKNFTTQPNFDVKRY--AGGWYDIEKTFFA--------G
	QMNKSCVKAEYSLRDDGKIDVLNQDYTAELHEENTTG---IAFYKDPNVKSKLTVKL-G
T	SP-----EANYWIVETDYDTYALIWSCA---ELEGIAHADIGW--ILGRKQR---LDE
NL	
>Silver-lipped_Oyster
-----------------KDCVISNFQTQSNFEADKF--VGKWYEIEWMTHQA---ENPND
	FW--DDYVTNYTLNDDGSFSLFTAFRSN--PNKTICSL-QNAVMYRTSN-AKYDV---A
V	SSCRQIRHSPQWIISTDYIRYAIIYSCHVQ-NIDGTCKTWVAK--TFSR-KRTLDDR-
-Y	
>Pacific_Oyster
------------RAQTGTCPVVSSISVQPGFDYESLANESRWNVVLYS--KIIPIEGLDM
	QVVKSDVSLMFSRDADNNKTVTLAGRVRLASSFAFCLKLQGSVEDSSEVPAKLRQSFYN
P	LTN-QFLDFNFWILHTDYTNLAVVYACEKIMAADGTCDPGSSYMWTLSRGTSHTAAE-
-R	
>Human
MNYSKIPAQVDLRRQTERDCRVSSFRVKENFDKARF--SGTW----YAMAKKDP-EGL--
	-FLQDNIVAEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDT-EDPAKFKMKYWG
V	ASFLQKGNDDHWIVDTDYDTYAVQYSCRLL-NLDGTCADSYSF--VFSRDPNGLPPE-
-A	
>Razor_Clam
------------------------------------------------------------
	-----------------------------------------------------------
-	----QVGMKPGWILTTDYENYAVIYSCWSE-QESGECHPSNTYVAVLQRKTDDISPS-
-H	
>Bay_Scallop
------------------------------------------------------------
	-----------------------------------------------------------
-	--------DAMWVVSTDYDGYAVTYGCDKVLPESGYCDPSKEAVYTLNRRQDGHTKQ-
-Q	
